### ISSUE TITLE
curators discuss (with complex annotation) need  guidelines how to annotate ubiquitination targets as substrates

### ISSUE THREAD

**Issue by pombase-admin** [pombase/curation#487] opened 2014-11-13 17:57 UTC
for the varius UB ligase complex components

F-box adaptor, E1, E2, E3, 

Original comment by: ValWood

**Comment by ValWood** [comment] 2019-09-26 14:12
duplicate of
https://github.com/pombase/curation/issues/2498

**Closed by ValWood** 2019-09-26 14:12 UTC
Labels: auto-migrated, discuss, next curator meeting, sourceforge
