### ISSUE TITLE
rehouse diploids

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#702] opened 2015-09-17 13:10 UTC
map1 mutant / map1 mutant,SPAC11E3.06:allele-4,cd202708cc47017a

hets
fus1-B20/fus1-B20,SPAC20G4.02c:allele-3,ef2da839886aa260
caf2-3 / WT,SPAC1805.17:allele-6,9076c0731474baf4
act1+/act1-,SPBC32H8.12c:allele-5,ed12ab2f3f0456f6
heterozygous diploid,SPAC17H9.09c:allele-15,a64b97197e845b5b
erg10+/erg10-,SPBC215.09c:allele-2,9a1022fd353bacb9
cam1+/cam1-,SPAC3A12.14:allele-2,894e3c36003ab516
mcs2+/mcs2-,SPBP16F5.02:allele-3,9a1022fd353bacb9
pik3+/pik3-,SPAC458.05:allele-5,ed12ab2f3f0456f6
alg9+/alg9-,SPAC1834.05:allele-3,9a1022fd353bacb9
SPBC19C2.10+/SPBC19C2.10-,SPBC19C2.10:allele-2,9a1022fd353bacb9
heterozygous diploid,SPAC4A8.12c:allele-3,c93df2f114eaee6e
cut12+/cut12-,SPBC649.05:allele-4,ed12ab2f3f0456f6
gea1+/gea1-,SPBC211.03c:allele-3,fa30fa9e2e0880e6
ste7-1/ste7-1 diploid,SPAC23E2.03c:allele-5,34e3d6fc4ce28886
asa1+/asa1-,SPAC1006.02:allele-2,9a1022fd353bacb9
suc1+/suc1-,SPBC1734.14c:allele-7,ed12ab2f3f0456f6
spi1+/spi1-,SPBC1289.03c:allele-2,894e3c36003ab516
rad24+/rad24-,SPAC8E11.02c:allele-4,894e3c36003ab516
its3+/its3-,SPAC19G12.14:allele-5,ed12ab2f3f0456f6
cut7+/cut7-,SPAC25G10.07c:allele-4,894e3c36003ab516
sum1+/sum1-,SPAC4D7.05:allele-5,ed12ab2f3f0456f6
tor2+/tor2-,SPBC216.07c:allele-12,ed12ab2f3f0456f6
cdc2+/cdc2-,SPBC11B10.09:allele-31,ed12ab2f3f0456f6
tif45+/tif45-,SPAC16E8.15:allele-2,ed12ab2f3f0456f6
mip1+/mip1-,SPAC57A7.11:allele-5,c22385c0fd392e28
tif35+/tif35-,SPBC18H10.03:allele-2,ed12ab2f3f0456f6
heterozygous diploid,SPBC1289.03c:allele-4,e113c7320f53efc5
dic1+/dic1-,SPBC646.17c:allele-2,9a1022fd353bacb9
top2+/top2-,SPBC1A4.03c:allele-6,894e3c36003ab516
tuf1+/tuf1-,SPBC9B6.04c:allele-3,ed12ab2f3f0456f6
spn3+/spn3-,SPBC16A3.01:allele-3,9a1022fd353bacb9
taf4+/taf4-,SPAC23G3.09:allele-2,9a1022fd353bacb9
byr2-/byr2-,SPBC1D7.05:allele-10,803cfb382ebb41c6

homos
int6-/int6-,SPBC646.09c:allele-4,2de3ef290c749683
cpc2-/cpc2-,SPAC6B12.15:allele-7,5e0bcd0a5a6d9347
gpa1-/gpa1-,SPBC24C6.06:allele-3,986cd0e5341a9fe8
homozygous diploid,SPAC1D4.13:allele-8,a64b97197e845b5b
pcr1-/pcr1-,SPAC21E11.03c:allele-5,aefacb75b8af3f8a
ste7-111/ste7-111,SPAC23E2.03c:allele-7,34e3d6fc4ce28886
ste4-/ste4-,SPAC1565.04c:allele-3,0dd384fe368bd279
ste7-delta/ste7-delta diploid,SPAC23E2.03c:allele-6,34e3d6fc4ce28886
ste7+/ste7+,SPAC23E2.03c:allele-8,34e3d6fc4ce28886
homozygous diploid,SPBC21.05c:allele-5,423a987e520829e2
zfs1-/zfs1- diploid,SPBC1718.07c:allele-3,67506e3e78c72666
fkh1-/fkh1-,SPBC839.17c:allele-3,ae029b5da42522e3
tor1-/tor1- diploid,SPBC30D10.10c:allele-6,3c604e8199f9bf8b
pac2+/pac2+ diploid,SPAC31G5.11:allele-4,e25a10ee7a1d5416
homozygous diploid,SPAC22H10.07:allele-5,423a987e520829e2
ste13-/ste13-,SPBC776.09:allele-5,e8aedfc4412e4268
moe1-/moe1-,SPAC637.07:allele-4,2de3ef290c749683
spk1-/spk1-,SPAC31G5.09c:allele-4,986cd0e5341a9fe8
ras1-/ras1-,SPAC17H9.09c:allele-13,803cfb382ebb41c6
map1-/map1-,SPAC11E3.06:allele-6,bf6ebbd7a7fa9fb9
homozygous diploid,SPAC16E8.09:allele-5,423a987e520829e2
sty1-/sty1-,SPAC24B11.06c:allele-11,87780c68f55805a1
atf1-/atf1-,SPBC29B5.01:allele-9,87780c68f55805a1
byr1-/byr1-,SPAC1D4.13:allele-7,803cfb382ebb41c6
srk1-/srk1-,SPCC1322.08:allele-5,ec6c2870725e0368
delta/delta,SPAC18B11.07c:allele-7,47797c5ac471b4da
skp1-/skp1-,SPAC1687.15:allele-3,d37836a2104d53bc

**Comment by mah11** [comment] 2015-09-17 13:12
is this a duplicate of #669?

**Comment by ValWood** [comment] 2015-09-17 14:00
oh yeah, bad memory

**Comment by mah11** [comment] 2015-09-17 14:56
ok, closing

**Closed by mah11** 2015-09-17 14:56 UTC
