### ISSUE TITLE
annotate wtf antidote structures (isoforms)

### ISSUE THREAD

**Issue by ValWood** [pombase/curation#2685] opened 2020-05-04 12:25 UTC
https://github.com/pombase/curation/issues/2264
From @lilindu

Yes, the "poison" transcript is also sense strand transcript and the reading frame is the same as the longer and already annotated "antidote" transcript. Maybe I should not have used the term "transcript" in my request of adding the annotation of the "poison" isoform. The wtf annotation file I sent you contains CDS annotations, not transcript annotations, as the first and the last exons are "coding exons" and do not correspond to the exons in the transcript. Thus, I think what I hope to add to the PomBase annotation is the annotation of the "poison" CDS.

For the "poison" transcripts of wtf4 and wtf13, the start codon of the "poison" CDS is inside intron 1. For the "poison" transcripts of wtf19 and wtf23, the start codon of the "poison" CDS is inside exon 2. Below are the coordinates of the first nucleotide of the start codon of the "poison" CDS for each of these 4 genes that are capable of expressing "poison" product:
wtf4: 222347
wtf13: 1581337
wtf19: 2018097
wtf23: 2146142

**Comment by ValWood** [comment] 2020-05-04 13:05
@kimrutherford 
@mah11 

Thoughts:

I can't remember how the protein ID form  is referenced in Canto as we haven't used it yet.
What format should they be.

Note that here I think we will be creating separate CDS (for the same loci, i.e shorter versions),   but I won't necessarily create a separate underlying transcript.

Once we have these structures the GO annotations need to hang on the protein isoforms.
I guess the way to do this is request for PRO ID's for these variations.

Once we have the Pro IDs  we can db_xfer them to the features.

(submitting these half thought so I don't lose them, in another meeting now)

**Comment by ValWood** [comment] 2020-05-04 15:48
@lilindu 2 questions.

1. Are the antidote isoforms identical  to the protein product of the full CDS only  shorter? (logically they must  be, but I just wanted to confirm).

2. Which of the currently annotated CDS are known to function  as poisons, but not antidotes and vice versa? ( For example, I was wondering if current  "pseudo" without the initiator methionine of a full- length toxin could still provide antidote activity (because then we  would probably more correctly  represent  these as a functional 'antidote' protein.

**Comment by lilindu** [comment] 2020-05-05 00:51
1. The full CDSs currently annotated correspond to the "antidote" CDS. The main difference between "antidote" CDS and "poison" CDS is that "antidote" CDS contains the amino acids coded by exon 1, whereas the shorter "poison" CDS does not.

2. Functional characterization of wtf genes in the reference strain is still limited in the published works. For the 25 wtf genes in the reference genome, only wtf13 has been experimentally demonstrated to be an active killer by the Zanders lab (PMID:30475921) (we have unpublished data supporting this conclusion), meaning that wtf13 must express both functional poison product and functional antidote product. In theory, no wtf genes should function as poison only, because it would be suicidal and be quickly eliminated during evolution. Indeed, based on Iso-Seq data, no wtf genes express only the short poison transcript. Most wtf genes (except for wtf4, wtf12, wtf13, wtf19, wtf23) do not express the short poison transcript, and theoretically can be regarded as antidote only, but because poison-antidote pairing has specificity, it is unclear whether a gene can be thought as a functional antidote (suppressor) if no matching poison has been found experimentally. Most of the 9 pseudogenes (except for wtf12) do not express the short poison transcript based on Iso-Seq data. wtf12 has pseudogenization mutations in the region shared by the poison CDS and the antidote CDS.

In sum, apart from wtf13, only three other non-pseudo wtf genes (wtf4, wtf19, wtf23) have potential to be functional killers because they express both the poison transcript and the antidote transcript. The other 12 non-pseudo wtf genes cannot be functional killers as they do not express the poison transcript, but I am not sure whether we can call them functional suppressors.

**Comment by ValWood** [comment] 2020-05-11 13:30
from @mah in skype chat 
https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008350

I still need to open tickets with proposed solution for variants/isoforms

**Comment by ValWood** [comment] 2020-09-05 10:11
@mah11 I assigned this to you too as I think https://github.com/pombase/curation/issues/2684
may be dependent on this?

I will start  the non wtf ones:
https://github.com/pombase/curation/issues/61
but it won't be for a couple of months...

**Comment by mah11** [comment] 2020-09-07 09:39
I don't have the file from Li-Lin. Could you attach it here or email it?

**Comment by ValWood** [comment] 2020-09-07 11:05
If I remember correctly the file from @lilindu was for the CDS coordinate updates which were done by me in 
https://github.com/pombase/curation/issues/2264

The outstanding task is to annotate the poison isoforms.
 I thought it might be better for you to do it as you are more familiar with the biology of the meiotic drivers, and I thought  the isoforms were in one of the Zanders papers that you approved. Perhaps not? 
This  will be an unusual case where  the GO annotations will be different for the different isoforms poison/antidote. So, I guess once the isoform IDs are created we will want Canto to display them as variants in the "gene product form extension". 

@lilindu do you know where the antidote isoforms are reported (if at all, maybe I misremembered)?

**Comment by lilindu** [comment] 2020-09-07 11:15
The CDS coordinate updates should have already led to correct annotations of all antidote isoforms. 

Only 4 genes have poison isoforms. Poison isoforms differ from antidote isoforms in the positions of the start codons.

The starting positions of the poison isoforms of the 4 genes are as follows:
wtf4: 222347
wtf13: 1581337
wtf19: 2018097
wtf23: 2146142

**Comment by kimrutherford** [comment] 2020-09-08 22:50
> I can't remember how the protein ID form is referenced in Canto as we haven't used it yet.

I don't know if you still need an answer to that question, but PomBase protein currently look like: SPCC18B5.03:pep
But I think we should probably change to something like: SPCC18B5.03.1:pep to handle the cases where there are multiple transcripts.

**Comment by ValWood** [comment] 2020-09-09 09:50
OK. This is what I imagine  will happen.

1. We create an alternative transcript with the  .2 suffix
2. The SPCC18B5.03 is already .1  behind the scenes (do we need to make that explicit?)
3. If the alternative transcript would generate a different protein isoform you store SPCC18B5.03.2:pep
4. In GO annotation  we add the  SPCC18B5.03.1:pep or  SPCC18B5.03.2:pep as the isoforms to distinguish the poison and antidote annotation forms

**Comment by kimrutherford** [comment] 2020-09-09 12:14
> The SPCC18B5.03 is already .1 behind the scenes (do we need to make that explicit?)

Kind of.  If you use /systematic_id="SPCC18B5.03" in a CDS feature in the contig file, then the code stores "SPCC18B5.03" as the ID of the gene in Chado and "SPCC18B5.03.1" is used as the automatically generated ID of the transcript stored in Chado.

It's been a long time since I've thought about this but I think code handles multiple transcripts by allowing /systematic_id="SPCC18B5.03.1"  (ie. with the ".1", ".2" etc.) for CDS features in the contig files.  In those cases the code should use "SPCC18B5.03" for the gene and "SPCC18B5.03.1" or whatever for the transcript.

So the summary is: use /systematic_id="SPCC18B5.03.1" in one CDS and systematic_id="SPCC18B5.03.2" in the other and hopefully that will work.  If not, I'll fixed it.

**Comment by mah11** [comment] 2020-09-11 12:37
> So the summary is: use /systematic_id="SPCC18B5.03.1" in one CDS and systematic_id="SPCC18B5.03.2" in the other and hopefully that will work.

OK, I've just committed a chr3 file (rev. 6490) where I did this for wtf19. It now has two CDSs, systematic_id="SPCC1906.03.1" and systematic_id="SPCC1906.03.2". I haven't changed anything else in the file, so it'll be easy to revert if it breaks anything. Exciting!

If it does work I'll go ahead and do wtf4, wtf13, and wtf23.

**Comment by kimrutherford** [comment] 2020-09-11 13:32
OK, thanks for the warning.  :-)

I'll check the results tomorrow.

**Comment by kimrutherford** [comment] 2020-09-12 02:32
The Chado loading partly worked.  The transcript feature and exon features were successfully added.  But we automatically make a feature for each intron and that didn't happen for transcript 2.  I'll fix that.

We also need to think about what to do with UTRs when they're known.

The code that creates the website failed:
> unimplemented - can't handle multiple transcripts for: SPCC1906.03

I forgot about that and it will need a bit of fixing.

I'll revert the contig change and add the second transcript back once things are working on my desktop.

**Comment by kimrutherford** [comment] 2020-09-12 02:38
> But we automatically make a feature for each intron and that didn't happen for transcript 2.

I was misremembering - transcript 1 has confirmed introns.  So it's actually fine.

This does need fixing though:
> unimplemented - can't handle multiple transcripts for: SPCC1906.03

**Comment by kimrutherford** [comment] 2020-09-12 06:26
> This does need fixing though:

It was a quick fix.  This is how the transcript section looks on my desktop.  The diagrams for the two transcripts are the same length which is deceptive.  I'll change the code so that they are the same scale.

![multi-transcript1](https://user-images.githubusercontent.com/90474/92989009-fb2ed680-f524-11ea-9f6f-9ca30a241d11.png)

**Comment by ValWood** [comment] 2020-09-12 08:01
nice - you'll also need to add the alternative to the sequence section .....

**Comment by kimrutherford** [comment] 2020-09-12 08:59
> you'll also need to add the alternative to the sequence section .....

Yep.  And we need to decide what to do with the protein feature section, and the "Product size" and "Genomic location" items at the top of the gene page.

What should we do when downloading protein sequences from the results page?  Currently the output only includes the first transcript and header looks like:
```>SPCC1906.03 SPCC1906.03|wtf19|wtf meiotic drive poison Wtf19```

Another two bugs:
  - in Chado the second transcript is missing an associated "polypeptide" feature
  - the feature type on my desktop for wft19 is currently "mRNA mRNA gene" instead of "protein coding"

I suspect the first of those bugs is causing the second.

I'll chip away at these problems.

**Comment by ValWood** [comment] 2020-09-12 10:11
>Yep. And we need to decide what to do with the protein feature section, and the "Product size" and "Genomic location" items at the top of the gene page.

For these, we should show the transcript/translation relating to  01 which we will try to make sure is the major isoform (this might sometimes be a bit arbitrary, but usually it will be the existing version.

For the download we should probably use the major isoform (for now), but add an additional field  to the header with the transcript identifier. 
We can decide later if we want to add an additional download option to include *all* transcripts/translations. Usually people will want only one sequence version per locus for most types of analyses.

**Comment by kimrutherford** [comment] 2020-09-13 02:07
> This is how the transcript section looks on my desktop.

The nightly load worked so both transcripts are visible in the transcript section:
  https://www.pombase.org/gene/SPCC1906.03

The other problems still need fixing.

**Comment by kimrutherford** [comment] 2020-09-13 04:00
> you'll also need to add the alternative to the sequence section .....

I've implemented that in the easiest way just so it working.  We can change the interface after discussion:

![sequence-transcript-select-1](https://user-images.githubusercontent.com/90474/93009845-c29d0480-f5d9-11ea-8798-4f9174275e8d.png)

That's live now: https://www.pombase.org/gene/SPCC1906.03

Also I hadn't noticed but the new transcript is now appearing in JBrowse, which is nice:
![jbrowse-multi-transcript-1](https://user-images.githubusercontent.com/90474/93009885-30e1c700-f5da-11ea-8997-016546c25c94.png)

**Comment by ValWood** [comment] 2020-09-13 07:45
This is all great!
I like the select a transcript to stitch otherwise it could get very cluttered.

Nice in JBrowse because you can more easily see the differences (since the transcripts are aligned)

Regarding the UTRs, if we know (or can assume)  that the  UTR structure is the same should we add an additional UTR with the correct transcript ID? (i.e. the 3' UTR here)?

Or,  should we infer that the UTR is shared *unless* we create an alternative UTR?  (if it would make sense, clearly it would not make sense to infer the 5' UTR here).

Which is easiest?

For wtf19 we probably know, or can locate the  antidote transcription start site. If so we  should  add this one explicity.

I will try to annotate most of the  alternatives in my list over the next few weeks
https://github.com/pombase/curation/issues/61
I suspect  Midori will be quicker with the wtfs. Once we have a  reasonable number of examples we can announce, and ask people for additional published alternative trancripts (not HTP).

**Comment by ValWood** [comment] 2020-09-13 07:48
We also need a way to retrieve genes with annotated alternative transcripts easily (query builder option).
I will opened a new  ticket for that. It can happen later, once we have annotated a few.
https://github.com/pombase/website/issues/1601

**Comment by kimrutherford** [comment] 2020-09-14 04:31
> I'll change the code so that they are the same scale.

I've scaled and aligned the transcripts.  Maybe it what be nice one day to have an option to hide the coordinates sections so that the transcript diagrams could be closer together?

![align-transcripts-1](https://user-images.githubusercontent.com/90474/93042898-6b179b00-f6a4-11ea-9069-934538584a9e.png)

**Comment by kimrutherford** [comment] 2020-09-14 04:38
> Which is easiest?

Less inferring is easier for me.  :-)

> if we know (or can assume) that the UTR structure is the same should we add an additional UTR with the correct transcript ID?

That's my preferred plan but we could probably do something cleverer.

**Comment by kimrutherford** [comment] 2020-09-14 04:44
> If it does work I'll go ahead and do wtf4, wtf13, and wtf23.

I was just about to open an issue about this warning while loading chromosome3.contig:
```
 /systematic_id=SPCC548.03c on misc_feature
```

but then I noticed that it was wtf4, so I didn't.  :-)

**Comment by kimrutherford** [comment] 2020-09-14 06:32
> if we know (or can assume) that the UTR structure is the same should we add an additional UTR with the correct transcript ID?

I've just done some testing (because I wasn't sure it worked) to check that we can add an intron or UTR with transcript ID and it does the right thing:
```
/systematic_id="SPCC1906.03.2"
```

It all works fine.

**Comment by ValWood** [comment] 2020-09-14 08:12
>I've scaled and aligned the transcripts. Maybe it what be nice one day to have an option to hide the coordinates sections so that the transcript diagrams could be closer together?

I was going to suggest that but did not want to give you more work.  The coordinates could be  hidden by default.

**Comment by ValWood** [comment] 2020-09-14 08:13
Nice to see them scaled and aligned too

**Comment by mah11** [comment] 2020-09-14 11:14
This is awesomely cool. 

> ... UTRs
> For wtf19 we probably know, or can locate the antidote transcription start site.

PMID:28631612 has an image of transcription start site data for wtf4, and cites PMID:27856494 for it (IIRC that's the one Li-Lin said had some errors - see https://github.com/pombase/curation/issues/2264#issuecomment-621837437). That's the only thing I've seen in the papers I've looked at (PMIDs 28631610, 28631612, 32032353; so no, I haven't seen anything for wtf19). Would Li-Lin have any relevant data?

Anyway, now that this is working, I'll update wtf4 and do wtf13 & wtf23. I'll use the existing 3' UTRs for both transcripts for all four, but I'll wait for more info before I do 5' UTRs.

And *no promises*, but now that I'm getting the hang of this I might be able to take on some of the transcripts from #61.

**Comment by lilindu** [comment] 2020-09-14 11:53
I will get the coordinates of the transcriptional start sites of the poison isoforms of these four genes from my student.

**Comment by mah11** [comment] 2020-09-14 12:03
@lilindu - thank you! That will help a lot.

**Comment by mah11** [comment] 2020-09-14 15:35
OK, these are pretty much done except for the 5' UTRs. When we have the poison transcript start sites I'll be able to finish it off.

**Comment by kimrutherford** [comment] 2020-09-14 21:52
> OK, these are pretty much done except for the 5' UTRs.

Thanks.  I did a test load on my desktop and it all looks good.  I'll check the website in the morning.

**Comment by kimrutherford** [comment] 2020-09-14 22:01
> The coordinates could be hidden by default.

Does this look OK?:
![no-coords-1](https://user-images.githubusercontent.com/90474/93142568-669dc180-f73a-11ea-8e51-d52055beb6bf.png)

**Comment by kimrutherford** [comment] 2020-09-15 02:40
wtf13 looks good in JBrowse and in the transcript gene page section: https://www.pombase.org/gene/SPCC162.04c

It's a good test of everything because you've added a UTR to the new transcript and wtf13 on the reverse strand, which often breaks things.

**Comment by ValWood** [comment] 2020-09-15 07:14
I can see "protein features" in the page, but the menu item has disappeared? It's still present on other pages...

**Comment by ValWood** [comment] 2020-09-15 07:15
But it looks great!

**Comment by kimrutherford** [comment] 2020-09-15 07:59
> I can see "protein features" in the page, but the menu item has disappeared?

The gene currently has a feature type of "mRNA mRNA gene" instead of "protein coding".  I think if I fix that then the menu item will come back - the menu has protein features only for protein coding genes.

**Comment by mah11** [comment] 2020-09-15 09:14
> wtf13 looks good in JBrowse and in the transcript gene page section

It does indeed. Hooray! (and whew.)

> Does this [pic with hidden coordinates] look OK?

Yes, and the show/hide toggle is working nicely too.

**Comment by lilindu** [comment] 2020-09-15 12:22
Based on our analysis of Kuang et al. Iso-Seq data, the transcriptional start sites of the poison isoforms of the 4 genes are as follows:
wtf4: 222403
wtf13: 1581396
wtf19: 2018018
wtf23: 2146063

**Comment by mah11** [comment] 2020-09-15 14:02
Thank you -- I've added the poison isoform 5' UTRs using those start sites.

I noticed that we don't have a 5' UTR annotated for the antidote isoform of wtf4. @lilindu do you know that start site? If so, I'll add it; otherwise, this ticket is finished (hooray).

**Comment by lilindu** [comment] 2020-09-15 14:55
Below are the coordinates of the transcriptional start sites of the antidote isoforms of the 4 genes:
wtf4: 222935
wtf13: 1581928
wtf19: 2017483
wtf23: 2145527

**Comment by mah11** [comment] 2020-09-15 16:31
Thank you again, and this is done!

**Closed by mah11** 2020-09-15 16:31 UTC
Labels: announce, waiting
