### ISSUE TITLE
"directly activates" and "directly inhibits"

### ISSUE THREAD

**Issue by mah11** [pombase/curation#2041] opened 2018-06-15 13:55 UTC
OWL GAF checks flagged these, so I've removed them from the GAF that's gone to GO central today. Same issue as in #1720 - they simply don't allow catalytic MFs with IPI evidence. (In these cases I also think the info in the extensions is only really going to work well in GO-CAMs.)

I haven't changed the annotations in Canto.

    GO_AR:0000007 IPI should not be used with catalytic activity molecular function terms Warning count:  2
    GO_AR:0000007   Warning IPI should not be used with catalytic activity molecular function terms PomBase SPAC17H9.09c    ras1            GO:0003924      PMID:7923372    IPI     PomBase:SPAC16E8.09     F       GTPase Ras1     ste5    protein taxon:4896      20180429        PomBase directly_positively_regulates(PomBase:SPAC16E8.09),part_of(GO:0071963)
    GO_AR:0000007   Warning IPI should not be used with catalytic activity molecular function terms PomBase SPBC1D7.05      byr2            GO:0004709      PMID:9315645    IPI     PomBase:SPAC1D4.13      F       MAP kinase kinase kinase Byr2   SPBC2F12.01|ste8        protein taxon:4896      20180429        PomBase directly_positively_regulates(PomBase:SPAC1D4.13),part_of(GO:0071507)

https://curation.pombase.org/pombe/curs/7537db502e936856/
https://curation.pombase.org/pombe/curs/c3f91b7bec8a34a1/

**Comment by Antonialock** [comment] 2018-06-15 16:32
Ah, cheers, I've sorted those out.

**Comment by ValWood** [comment] 2018-06-15 16:54
> In these cases I also think the info in the extensions is only really going to work well in GO-CAMs

Which info in which extensions?

**Comment by Antonialock** [comment] 2018-06-15 16:58
I changed them to EXP's as a stopgap until we have a better solution. I don't think the annotations are wrong.

**Comment by ValWood** [comment] 2018-06-15 17:04
We know there is a problem with the relationship because it refers to the gene here and we want to refer to the activity, so we need a solution for that but there are tickets about this. Is there another issue  that we don't know about?

**Comment by Antonialock** [comment] 2018-06-16 08:45
I don't understand what the problem is? (aside from that I used IPI with catalytic MF?)

**Comment by mah11** [comment] 2018-06-18 13:04
1. The part_of(GO:BP) extensions pose no problem at all.

> We are using "positively directly regulates" and "negatively directly regulates"
to mean regulates the activity of x, but what we are actually saying is "regulates the gene x"
so, when we submit to GO we need to switch these to has_substrate.

2. For the byr2 GO:0004709 annotation, this is basically it, although there is one aspect that Val's comment doesn't explicitly cover: computers can't do everything that humans can. As I understand it, reasoning won't infer a couple of things that we (and our users) get intuitively:

 - that the first gp regulates the second gp by modifying it (in other words, reasoning doesn't infer the connection that gp1-modifies-gp2 is the mechanism by which gp1 regulates gp2's activity)
 - which activity of the substrate is being regulated, even when the substrate has only one activity annotated

For the first point, a new extension relation for "regulates activity of by modifying" should do the trick. For the second, I'm not even 100% sure we get all the way there with a new relation; it needs the "nesting" that can only be done in GO-CAMs.

There's some discussion in https://github.com/geneontology/annotation_extensions/issues/63, but the comment thread there is lo-o-o-ng and the stuff about what we want to do is really buried. Good luck. If we want to renew efforts with GO to try to get new relations I can try to draft a new ticket.

3. There's another issue with the ras1 GO:0003924 annotation, in addition to the stuff noted above. For that one we can't even use has_substrate as our placeholder for GO, because the substrate of any GTPase activity is, wait for it, GTP. It would be utter nonsense to put a gp identifier in as a GTPase substrate, and reasoning could do nothing with it. This also means the proposed new regulates-by-modifying relation would be irrelevant and unhelpful.

Reasoning aside, I also find it a lot less intuitive to figure out what's going on in this case. How does hydrolyzing GTP regulate any activity of Scd1?

**Comment by ValWood** [comment] 2018-06-19 13:41
Yep I think behind the scenes we will need to do something nested to connect these, but we don't want to plonk all of that  part on the gene pages.

Let's leave this part until the curator meeting. My head is full right now.
One of the exercises I wanted to try is to put a very small model into noctua (ie just 2 connected genes)...... and see what comes out....I haven't summoned the will to do this yet...

I don't know about the connection between ras1 and scd2, Antonia will need to answer that one

**Comment by ValWood** [comment] 2018-06-19 13:42
@Antonialock  once you are don, unassign youself,  and assign to me. I want to keep it to remind me to put it on the list for the curator meeting.

**Comment by Antonialock** [comment] 2018-06-21 16:18
> Reasoning aside, I also find it a lot less intuitive to figure out what's going on in this case. How does hydrolyzing GTP regulate any activity of Scd1?

good point...Looks like I wanted a MF to stick the extension on. Maybe it just has to go on a binding annotation.

**Comment by Antonialock** [comment] 2018-06-21 16:18
i'll get it fixed when I look at this next

**Comment by ValWood** [comment] 2018-06-21 19:12
Keep yourself assigned until fixed.
I have it on my list now.

**Comment by ValWood** [comment] 2019-12-02 20:36
[gpad-from-cdc25-cdc2-model.txt](https://github.com/pombase/curation/files/3913207/gpad-from-cdc25-cdc2-model.txt)

**Comment by ValWood** [comment] 2021-07-09 08:32
fix
https://curation.pombase.org/pombe/curs/05ebdc773cdd0a9d/feature/gene/view/7

**Comment by ValWood** [comment] 2024-07-10 19:10
out of date

**Closed by ValWood** 2024-07-10 19:10 UTC
Labels: GO-CAM
